on:
  push:
    branches:
      - main
      - wip # V3
    paths:
      - 'docs/**'

name: Deploy seed-design-v3 docs (Production)

jobs:
  deploy:
    name: Deploy Seed Design V3 Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          cache: yarn
      
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Packages
        run: yarn build-only-package

      - name: Build Docs
        working-directory: ./docs
        run: |
          yarn build
      
      - name: Deploy docs at Cloudflare Pages in `seed-design-v3` project (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./docs/out --project-name=seed-design-v3 --branch=main
